services:
  - type: web
    name: bucket-list
    env: python
    buildCommand: |
      curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      apt-get install -y nodejs
      pip install -r requirements.txt
      python manage.py tailwind install
      npm install
      python manage.py tailwind build
      python manage.py collectstatic --noinput
    startCommand: gunicorn bucket_list.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com 