services:
  - type: web
    name: bucket-list
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bucket_list.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: False
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com 